# This is a basic workflow to help you get started with Actions

name: build_win

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_win:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Get thirdParty cache
        id: cache-thirdParty
        uses: actions/cache@v2
        with:
          path: |
            third_party
            vendor_tools
          key: third_party-win-${{ hashFiles('DEPS') }}-${{ hashFiles('vendor.json') }}
          restore-keys: third_party-win-

      - name: Get environment cache
        id: cache-environment
        uses: actions/cache@v2
        with:
          path: |
            npm_cache
          key: libpag-win-environment-20220402
          restore-keys: libpag-win-environment
      - name: Check cache-environment status
        if: steps.cache-environment.outputs.cache-hit != 'true'
        run: |
          rm -rf npm_cache
          mkdir npm_cache
          cd npm_cache
          npm install depsync
        shell: bash

      - if: github.event_name == 'push'
        name: Build cache（push）
        run: |
          npm_cache/node_modules/depsync/bin/depsync
          node build_vendor -p win

      - if: github.event_name == 'pull_request'
        name: Windows build
        run: |
          npm_cache/node_modules/depsync/bin/depsync
          node ./vendor_tools/cmake-build pag -p win -a x64 -o ./win/paglib -v -i -DPAG_BUILD_SHARED=ON
        shell: bash